[package]
name = "flows_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { workspace = true }
gpui-component = { workspace = true }
workspace = { path = "../workspace" }
ui = { path = "../ui" }
